<#
.SYNOPSIS
    One-time setup: provision the Azure Storage resources that hold Terraform
    remote state and write backend.hcl ready for use with:

        terraform init -backend-config=backend.hcl

.DESCRIPTION
    Creates a resource group, storage account (HTTPS-only, TLS 1.2, versioning
    enabled), and blob container, then writes backend.hcl in the repo root.
    Safe to re-run — exits early if backend.hcl already exists.

.PARAMETER ResourceGroup
    Name of the resource group to create for state storage.
    Default: rg-nexus-tf-state

.PARAMETER Location
    Azure region for the resource group and storage account.
    Default: uksouth

.EXAMPLE
    .\scripts\create-backend.ps1
    .\scripts\create-backend.ps1 -ResourceGroup my-tf-state -Location westeurope
#>

[CmdletBinding()]
param(
    [string] $ResourceGroup = 'rg-nexus-tf-state',
    [string] $Location      = 'uksouth'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$Container  = 'tfstate'
$Key        = 'nexus-oss.terraform.tfstate'
$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$RootDir    = Split-Path -Parent $ScriptDir
$BackendHcl = Join-Path $RootDir 'backend.hcl'

# ---------------------------------------------------------------------------
# Guard: exit early if already set up
# ---------------------------------------------------------------------------
if (Test-Path $BackendHcl) {
    $sa = (Select-String 'storage_account_name' $BackendHcl).Line -replace '.*=\s*"([^"]+)".*', '$1'
    Write-Host "backend.hcl already exists (storage account: $sa)."
    Write-Host 'Delete backend.hcl to force recreation, or keep this one and run:'
    Write-Host '  terraform init -backend-config=backend.hcl'
    exit 0
}

# ---------------------------------------------------------------------------
# Verify Azure login
# ---------------------------------------------------------------------------
Write-Host '==> Checking Azure login ...'
try {
    $account = az account show | ConvertFrom-Json
} catch {
    Write-Error 'Not logged in — run: az login'
    exit 1
}
Write-Host "    Using subscription: $($account.name)"

# ---------------------------------------------------------------------------
# Storage account name (globally unique)
# ---------------------------------------------------------------------------
$Suffix    = -join ((97..122) + (48..57) | Get-Random -Count 6 | ForEach-Object { [char]$_ })
$SaName    = "sttfstate$Suffix"

Write-Host "==> Creating resource group '$ResourceGroup' in $Location ..."
az group create --name $ResourceGroup --location $Location --output none

Write-Host "==> Creating storage account '$SaName' ..."
az storage account create `
    --name                    $SaName `
    --resource-group          $ResourceGroup `
    --location                $Location `
    --sku                     Standard_LRS `
    --https-only              true `
    --min-tls-version         TLS1_2 `
    --allow-blob-public-access false `
    --output                  none

Write-Host '==> Enabling blob versioning (enables state file recovery) ...'
az storage account blob-service-properties update `
    --account-name   $SaName `
    --resource-group $ResourceGroup `
    --enable-versioning true `
    --output none

Write-Host "==> Creating blob container '$Container' ..."
az storage container create `
    --name         $Container `
    --account-name $SaName `
    --auth-mode    login `
    --output       none

# ---------------------------------------------------------------------------
# Write backend.hcl
# ---------------------------------------------------------------------------
Write-Host "==> Writing $BackendHcl ..."
@"
# Auto-generated by scripts/create-backend.ps1 -- do not commit (git-ignored).
resource_group_name  = "$ResourceGroup"
storage_account_name = "$SaName"
container_name       = "$Container"
key                  = "$Key"
"@ | Set-Content -Path $BackendHcl -Encoding UTF8

Write-Host ''
Write-Host '============================================================'
Write-Host " Backend storage ready."
Write-Host " Storage account : $SaName"
Write-Host " Resource group  : $ResourceGroup"
Write-Host " Subscription    : $($account.name)"
Write-Host ''
Write-Host ' Next step:'
Write-Host '   terraform init -backend-config=backend.hcl'
Write-Host '============================================================'
