<#
.SYNOPSIS
    One-time setup: provision the Azure Storage resources that hold Terraform
    remote state and write backend.hcl ready for use with:

        terraform init -backend-config=backend.hcl

.DESCRIPTION
    Creates a resource group, storage account (HTTPS-only, TLS 1.2, versioning
    enabled), and blob container, then writes backend.hcl in the repo root.
    Safe to re-run — exits early if backend.hcl already exists.

.PARAMETER ResourceGroup
    Name of the resource group containing the shared state storage account.
    Default: rg-terraform-state

.PARAMETER StorageAccount
    Name of the shared Azure Storage account for Terraform state.
    Default: sttfstateukhtbs01

.PARAMETER Location
    Azure region for the resource group and storage account.
    Default: uksouth

.EXAMPLE
    .\scripts\create-backend.ps1
    .\scripts\create-backend.ps1 -ResourceGroup my-tf-state -Location westeurope
#>

[CmdletBinding()]
param(
    [string] $ResourceGroup = 'rg-terraform-state',
    [string] $StorageAccount = 'sttfstateukhtbs01'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$Container  = 'terraform-nexus-oss-azure'
$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$RootDir    = Split-Path -Parent $ScriptDir
$InfraBackendHcl = Join-Path $RootDir 'infra/backend.hcl'
$NexusBackendHcl = Join-Path $RootDir 'nexus/backend.hcl'

# ---------------------------------------------------------------------------
# Verify Azure login
# ---------------------------------------------------------------------------
Write-Host '==> Checking Azure login ...'
try {
    $account = az account show | ConvertFrom-Json
} catch {
    Write-Error 'Not logged in — run: az login'
    exit 1
}
Write-Host "    Using subscription: $($account.name)"

# ---------------------------------------------------------------------------
Write-Host "==> Creating blob container '$Container' ..."
az storage container create `
    --name         $Container `
    --account-name $StorageAccount `
    --auth-mode    login `
    --output       none

# ---------------------------------------------------------------------------
# Write phase backend configurations
# ---------------------------------------------------------------------------
Write-Host "==> Writing $InfraBackendHcl and $NexusBackendHcl ..."
@"
# Auto-generated by scripts/create-backend.ps1 -- do not commit (git-ignored).
resource_group_name  = "$ResourceGroup"
storage_account_name = "$StorageAccount"
container_name       = "$Container"
key                  = "dev/infra.tfstate"
"@ | Set-Content -Path $InfraBackendHcl -Encoding UTF8
@"
# Auto-generated by scripts/create-backend.ps1 -- do not commit (git-ignored).
resource_group_name  = "$ResourceGroup"
storage_account_name = "$StorageAccount"
container_name       = "$Container"
key                  = "dev/nexus.tfstate"
"@ | Set-Content -Path $NexusBackendHcl -Encoding UTF8

Write-Host ''
Write-Host '============================================================'
Write-Host " Backend storage ready."
Write-Host " Storage account : $StorageAccount"
Write-Host " Resource group  : $ResourceGroup"
Write-Host " Subscription    : $($account.name)"
Write-Host ''
Write-Host ' Next step:'
Write-Host '   terraform init -backend-config=backend.hcl'
Write-Host '============================================================'
