#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# One-time setup: provision the Azure Storage resources that hold Terraform
# remote state and write backend.hcl ready for use with:
#
#   terraform init --backend-config=backend.hcl
#
# Usage:
#   ./scripts/create-backend.sh [resource-group] [location]
#
# Defaults:
#   resource-group = rg-nexus-tf-state
#   location       = uksouth
#
# Safe to re-run — if backend.hcl already exists the script exits early.
# ---------------------------------------------------------------------------
set -euo pipefail

RG="${1:-rg-nexus-tf-state}"
LOCATION="${2:-uksouth}"
CONTAINER="tfstate"
KEY="nexus-oss.terraform.tfstate"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
BACKEND_HCL="$ROOT_DIR/backend.hcl"

# ---------------------------------------------------------------------------
# Guard: exit early if already set up
# ---------------------------------------------------------------------------
if [ -f "$BACKEND_HCL" ]; then
  SA=$(grep storage_account_name "$BACKEND_HCL" | sed 's/.*= *//' | tr -d '"' | tr -d ' ')
  echo "backend.hcl already exists (storage account: $SA)."
  echo "Delete backend.hcl to force recreation, or keep this one and run:"
  echo "  terraform init --backend-config=backend.hcl"
  exit 0
fi

# ---------------------------------------------------------------------------
# Verify Azure login
# ---------------------------------------------------------------------------
echo "==> Checking Azure login ..."
az account show --output none 2>/dev/null \
  || { echo "ERROR: not logged in — run: az login"; exit 1; }

SUBSCRIPTION=$(az account show --query name -o tsv)
echo "    Using subscription: $SUBSCRIPTION"

# ---------------------------------------------------------------------------
# Storage account (globally unique name)
# ---------------------------------------------------------------------------
SUFFIX=$(LC_ALL=C tr -dc 'a-z0-9' < /dev/urandom | head -c 6)
SA_NAME="sttfstate${SUFFIX}"

echo "==> Creating resource group '$RG' in $LOCATION ..."
az group create \
  --name     "$RG" \
  --location "$LOCATION" \
  --output   none

echo "==> Creating storage account '$SA_NAME' ..."
az storage account create \
  --name                   "$SA_NAME" \
  --resource-group         "$RG" \
  --location               "$LOCATION" \
  --sku                    Standard_LRS \
  --https-only             true \
  --min-tls-version        TLS1_2 \
  --allow-blob-public-access false \
  --output                 none

echo "==> Enabling blob versioning (enables state file recovery) ..."
az storage account blob-service-properties update \
  --account-name   "$SA_NAME" \
  --resource-group "$RG" \
  --enable-versioning true \
  --output none

echo "==> Creating blob container '$CONTAINER' ..."
az storage container create \
  --name         "$CONTAINER" \
  --account-name "$SA_NAME" \
  --auth-mode    login \
  --output       none

# ---------------------------------------------------------------------------
# Write backend.hcl
# ---------------------------------------------------------------------------
echo "==> Writing $BACKEND_HCL ..."
cat > "$BACKEND_HCL" << EOF
# Auto-generated by scripts/create-backend.sh — do not commit (git-ignored).
resource_group_name  = "$RG"
storage_account_name = "$SA_NAME"
container_name       = "$CONTAINER"
key                  = "$KEY"
EOF

echo ""
echo "============================================================"
echo " Backend storage ready."
echo " Storage account : $SA_NAME"
echo " Resource group  : $RG"
echo " Subscription    : $SUBSCRIPTION"
echo ""
echo " Next step:"
echo "   terraform init --backend-config=backend.hcl"
echo "============================================================"
