#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# One-time setup: provision the Azure Storage resources that hold Terraform
# remote state and write backend.hcl ready for use with:
#
#   terraform init --backend-config=backend.hcl
#
# Usage:
#   ./scripts/create-backend.sh [resource-group] [storage-account]
#
# Defaults:
#   resource-group = rg-terraform-state
#   storage-account = sttfstateukhtbs01
#
# Safe to re-run — if backend.hcl already exists the script exits early.
# ---------------------------------------------------------------------------
set -euo pipefail

RG="${1:-rg-terraform-state}"
SA_NAME="${2:-sttfstateukhtbs01}"
CONTAINER="terraform-nexus-oss-azure"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
INFRA_BACKEND_HCL="$ROOT_DIR/infra/backend.hcl"
NEXUS_BACKEND_HCL="$ROOT_DIR/nexus/backend.hcl"

# ---------------------------------------------------------------------------
# Verify Azure login
# ---------------------------------------------------------------------------
echo "==> Checking Azure login ..."
az account show --output none 2>/dev/null \
  || { echo "ERROR: not logged in — run: az login"; exit 1; }

SUBSCRIPTION=$(az account show --query name -o tsv)
echo "    Using subscription: $SUBSCRIPTION"

# ---------------------------------------------------------------------------
echo "==> Creating blob container '$CONTAINER' ..."
az storage container create \
  --name         "$CONTAINER" \
  --account-name "$SA_NAME" \
  --auth-mode    login \
  --output       none

# ---------------------------------------------------------------------------
# Write phase backend configurations
# ---------------------------------------------------------------------------
echo "==> Writing $INFRA_BACKEND_HCL and $NEXUS_BACKEND_HCL ..."
cat > "$INFRA_BACKEND_HCL" << EOF
# Auto-generated by scripts/create-backend.sh — do not commit (git-ignored).
resource_group_name  = "$RG"
storage_account_name = "$SA_NAME"
container_name       = "$CONTAINER"
key                  = "dev/infra.tfstate"
EOF
cat > "$NEXUS_BACKEND_HCL" << EOF
# Auto-generated by scripts/create-backend.sh — do not commit (git-ignored).
resource_group_name  = "$RG"
storage_account_name = "$SA_NAME"
container_name       = "$CONTAINER"
key                  = "dev/nexus.tfstate"
EOF

echo ""
echo "============================================================"
echo " Backend storage ready."
echo " Storage account : $SA_NAME"
echo " Resource group  : $RG"
echo " Subscription    : $SUBSCRIPTION"
echo ""
echo " Next step:"
echo "   terraform init --backend-config=backend.hcl"
echo "============================================================"
