name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: TobyAnscombe/github-actions/.github/workflows/terraform-ci.yml@main
    with:
      terraform_version: "~> 1.5"
      tflint_version: "v0.55.0"
      working_directory: "."
      trivy_severity: "HIGH,CRITICAL"
